### ISSUE TITLE
Add golang support to arm64

### ISSUE THREAD

**Issue by kylecannon** [actions/partner-runner-images#13]
in the normal amd64 builds go is included while it's not here. 

  /bin/sh: 1: go: not found

**Comment by jasonrandrews** [comment]
Thank you for reporting it. I will get it fixed.

**Comment by rizwan-r-r** [comment]
#7 #12 #14 #6 #9

**Comment by jasonrandrews** [comment]
@kylecannon 
go is now added in both Ubuntu 22.04 and 24.04, it is installed from the package manager.

**Comment by markvai** [comment]
@jasonrandrews 
What version is installed? I see 1.18 on the latest images? Which is quite old

**Comment by jasonrandrews** [comment]
Hello, the current version is 1.22.2 in the Arm runner images. 

If you see something older, you likely have an old runner. 

If you have a private repository, you should re-create the runner with the latest image. Check the details at https://learn.arm.com/learning-paths/cross-platform/github-arm-runners/runner/ 

Public repos will automatically pick up the latest image. 

The current image version is 0.0.11 for both Ubuntu 22.04 and 24.04

Here is the version output:

`go version go1.22.2 linux/arm64`
