### ISSUE TITLE
Add Swift to arm64 images

### ISSUE THREAD

**Issue by jsonfry** [actions/partner-runner-images#20]
Swift is present in the x86 images, but not in the arm64 images.

I see it says it's not supported in the readme, but is it possible to add it?

**Comment by jasonrandrews** [comment]
Hi @jsonfry 
I'll take a look and see if swift is possible to add.

**Comment by jasonrandrews** [comment]
@jsonfry 
I have added Swift to the Ubuntu 22.04 and 24.04 images, give it a try.

**Comment by jsonfry** [comment]
That's worked brilliantly, thanks for a speedy response!

**Comment by jasonrandrews** [comment]
Glad it worked.
