### ISSUE TITLE
YAML labels not documented for arm64 runners

### ISSUE THREAD

**Issue by ssbarnea** [actions/partner-runner-images#22]
Please document the YAML labels that we are supposed to be able to use for testing/using the arm64 images. While we seen documentation regarding what is baked in, it seems that the effective labels for picking suck runners are not documented.

I would expect something like `ubuntu-22.04-arm64` as a label, but that is nowhere written.

**Comment by lkfortuna** [comment]
Hi there - there are no labels for Arm runners at this time. You need to create your own runner and then you decide the naming of that runner. For more information see our documentation on how to create runners: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners
