### ISSUE TITLE
Add nvm

### ISSUE THREAD

**Issue by alxgrk** [actions/partner-runner-images#3]
_(partially taken from https://github.com/actions/runner-images/issues/4)_

**Tool information**

    Tool name: nvm
    Add or update? Add
    Desired version: latest
    Approximate size:
    If this is an add request:
        Brief description of tool: install/switch between Node.js versions, auto-installs & uses the node version as specified in a project’s .nvmrc file
        URL for tool's homepage: https://github.com/nvm-sh/nvm

**Can this tool be installed during the build?**

Yes, but not easily. See https://github.com/orgs/community/discussions/25061

**Comment by jasonrandrews** [comment]
Hi @alxgrk,

Thank you for the request, nvm does run on arm64 so it is possible to add it in the future. 
I'll put it on the consideration list for the next image build. 
Let me know if you need any help to use nvm on the current image. 

Thanks,
Jason

**Comment by jasonrandrews** [comment]
Hi @alxgrk 
nvm is now available on Ubuntu 22.04 using the installation process from actions/runner-images
